/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    BarChart: typeof import('./src/shared/components/common/barChart/index.vue')['default']
    Cm: typeof import('./src/features/cm/index.vue')['default']
    CmSearch: typeof import('./src/features/cm/components/CmSearch/CmSearch.vue')['default']
    CmTable: typeof import('./src/features/cm/components/CmTable/CmTable.vue')['default']
    Dd: typeof import('./src/features/dd/index.vue')['default']
    DdAiDiagInfo: typeof import('./src/features/dd/components/DdAiDiagInfo/DdAiDiagInfo.vue')['default']
    DdImageInfo: typeof import('./src/features/dd/components/DdImageInfo/DdImageInfo.vue')['default']
    DdImageView: typeof import('./src/features/dd/components/DdImageView/DdImageView.vue')['default']
    DdPatientInfo: typeof import('./src/features/dd/components/DdPatientInfo/DdPatientInfo.vue')['default']
    DdReportInfo: typeof import('./src/features/dd/components/DdReportInfo/DdReportInfo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Fu: typeof import('./src/features/fu/index.vue')['default']
    FuBulkPreview: typeof import('./src/features/fu/components/FuBulkPreview/FuBulkPreview.vue')['default']
    FuFooter: typeof import('./src/features/fu/components/FuFooter/FuFooter.vue')['default']
    FuSinglePreview: typeof import('./src/features/fu/components/FuSinglePreview/FuSinglePreview.vue')['default']
    FuUpload: typeof import('./src/features/fu/components/FuUpload/FuUpload.vue')['default']
    Layout: typeof import('./src/shared/layout/index.vue')['default']
    Loading: typeof import('./src/shared/components/common/Loading/Loading.vue')['default']
    Login: typeof import('./src/shared/components/business/login/index.vue')['default']
    Nav: typeof import('./src/shared/components/business/nav/index.vue')['default']
    RadarChart: typeof import('./src/shared/components/common/radarChart/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/shared/components/common/svgIcon/index.vue')['default']
  }
}
